name: Manually triggered workflow to create dist folder
on:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7.3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.3
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Build dist
        run: |
          sudo dpkg-reconfigure locales
          pipenv install --dev
          pipenv run pyinstaller --add-data 'templates:templates' app.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-fermeture-caisse-dist
          path: dist
          retention-days: 5
          
